import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import CalculatorImg from "../../public/Image/Calculator-Project-hnNB6sPE.png";
import DropboxImg from "../../public/Image/Dropbox_Website-DEFhZlgL.jpg";
import DiceGameImg from "../../public/Image/Dice-Game-CuU3z2am.png";
import LandRoverImg from "../../public/Image/LandRover-website-UCCNEH49.png";
import NetflixImg from "../../public/Image/Netflix-D62E3E4z.png";
import GitImg from "../../public/Image/github-DAmmr68n.png";
import LinkedIn from "../../public/Image/linkedin-DvbM5N3o.png";
import Instagram from "../../public/Image/instagram-VUFQ3l_n.png";
import Whatsapp from "../../public/Image/whatsapp-Bv3ceAgd.png";
import Profile from "../../public/Image/Media.png";
import { useEffect, useState } from "react";
import { MdLightMode } from "react-icons/md";
import { MdDarkMode } from "react-icons/md";
import ScrollDown from "../../public/Image/scroll-down.gif";
import { MdMarkEmailRead } from "react-icons/md";

export default function Home() {
  const [theme, setTheme] = useState("dark");

  useEffect(() => {
    // Check localStorage for user's theme preference
    const savedTheme = localStorage.getItem("theme");
    if (savedTheme) {
      setTheme(savedTheme);
    } else {
      setTheme("light"); // Default to light mode
    }
  }, []);

  useEffect(() => {
    // Apply the theme to the document body
    if (theme === "dark") {
      document.body.classList.add("bg-dark", "text-light");
      document.body.classList.remove("bg-light", "text-dark");
      localStorage.setItem("theme", "dark");
    } else {
      document.body.classList.add("bg-light", "text-dark");
      document.body.classList.remove("bg-dark", "text-light");
      localStorage.setItem("theme", "light");
    }
  }, [theme]);

  const toggleTheme = () => {
    setTheme((prevTheme) => (prevTheme === "light" ? "dark" : "light"));
  };
  return (
    <>
      <Head>
        <title>Kiran Gawande</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <main className={styles.main}>
          {/* header  */}
          <nav
            className={`navbar navbar-expand-lg position-fixed w-100 ${styles.navbar}`}
          >
            <div className="container-fluid">
              <Link className={`navbar-brand ${styles.navbrand} `} href="/">
                {/* <Image src="../../public/next.svg" alt="logo" width={50} height={50} quality={100} /> */}
                <Image
                  className={styles.profilepic}
                  src={Profile}
                  height={30}
                  width={30}
                  alt="profile"
                  quality={100}
                />{" "}
                Kiran Gawande
              </Link>

              <div className="collapse navbar-collapse" id="navbarNav">
                <ul
                  className={`navbar-nav ms-auto align-items-center ${styles.customNavLinks}`}
                >
                  <li className="nav-item">
                    <Link
                      className="nav-link active"
                      aria-current="page"
                      href="#scrollspyHeading1"
                    >
                      Home
                    </Link>
                  </li>
                  <li className="nav-item">
                    <Link className="nav-link" href="#scrollspyHeading2">
                      About
                    </Link>
                  </li>
                  <li className="nav-item">
                    <Link className="nav-link" href="#scrollspyHeading3">
                      Projects
                    </Link>
                  </li>

                  {/* <li className="nav-item">
                    <Link className="nav-link" href="#scrollspyHeading4">
                     Contact
                    </Link>
                  </li> */}
                </ul>
              </div>
              <button
                onClick={toggleTheme}
                className={`btn btn-outline-none ms-auto ${styles.modeButtons} `}
              >
                {theme === "light" ? <MdDarkMode /> : <MdLightMode />}
              </button>

              <button
                className="navbar-toggler"
                type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarNav"
                aria-controls="navbarNav"
                aria-expanded="false"
                aria-label="Toggle navigation"
              >
                <span className="navbar-toggler-icon" />
              </button>
            </div>
          </nav>

          {/* body  */}

          <div>
            <div>
              <div
                data-bs-spy="scroll"
                data-bs-target="#navbar-example2"
                data-bs-root-margin="0px 0px -40%"
                data-bs-smooth-scroll="true"
                className="scrollspy-example  rounded-2 mt-4"
                tabIndex={0}
              >
                <span id="scrollspyHeading1" className="mb-0"></span>
                <div className={` ${styles.divContainer}  `}>
                  <h1 className={`${styles.mainHeading} `}> Kiran Gawande</h1>
                  <h5 className={`w-50 ${styles.mainHeadingPara} `}>
                    {" "}
                    Skilled Web Developer with experience in building responsive
                    and user-friendly web application using React.js and
                    Next.js. Seeking contribute technical expertise and
                    creativity to a dynamic team.
                  </h5>

                  <div>
                    <a
                      className="btn btn-primary  p-0 mt-3"
                      href="/resume.pdf"
                      download
                    >
                      <button className={` ${styles.resumeBtn} btn text-white`}>
                        Resume
                      </button>
                    </a>

              
                  </div>
                  <Image
                    className={styles.scrollDown}
                    src={ScrollDown}
                    alt="scroll-down"
                    height={60}
                    width={60}
                    quality={100}
                  />
                </div>

                <span id="scrollspyHeading2"></span>

                <div className={` ${styles.divContainer}  `}>
                  <h3 className={` mt-5 pt-5 ${styles.divMainText}  `}>
                    About
                  </h3>

                  <div className="w-75 text-start">
                    <h5> About Me:</h5>
                    <p>
                      {" "}
                      I'm a Frontend-Focused Web Developer, dedicated to
                      building and managing the frontend of websites and web
                      applications. My goal is to ensure that each project I
                      work on contributes to the overall success of the product.
                      With a strong focus on user experience and performance, I
                      specialize in creating dynamic, responsive, and visually
                      appealing web interfaces.{" "}
                    </p>

                    <h5> What I Do: </h5>

                    <ul>
                      <li>
                        Develop and manage the frontend aspects of websites and
                        web applications.
                      </li>

                      <li>
                        Implement modern web technologies to ensure seamless,
                        user-friendly experiences.
                      </li>

                      <li>
                        Focus on performance optimization, responsiveness, and
                        scalability.
                      </li>

                      <li>
                        Continuously explore and learn new technologies to
                        enhance my skills and provide value to the projects I
                        work on.
                      </li>
                    </ul>

                    <h5> Sharing Knowledge: </h5>

                    <p>
                      {" "}
                      I am passionate about sharing the knowledge I've gained
                      over the years in web development. I contributes on many
                      projects eg. HDFC Credila on Nextjs, HDFC Bleu on Strapi
                      and Reactjs and War (Employee Management System ) on
                      Nextjs. Having Experience of Bitbucket ane Git On my
                      LinkedIn and Instagram, I regularly post valuable content
                      aimed at helping the developer community grow and learn.
                      Feel free to connect or follow me if you're interested in
                      web development tips, tutorials, or insights.{" "}
                    </p>

                    <h5> Open to Opportunities: </h5>

                    <p>
                      I’m always open to new job opportunities where I can
                      contribute, learn, and grow as a developer. If you have a
                      project or position that aligns with my skills and
                      experience, don't hesitate to reach out! Let's connect and
                      discuss how we can collaborate.
                    </p>
                  </div>

                  <h3 className={` mt-5 pt-5 ${styles.divMainText}  `}>
                    Skills
                  </h3>

                  <div className="tag-list">
                    <div
                      className="loop-slider"
                      style={{
                        "--duration": "15951ms",
                        "--direction": "normal",
                      }}
                    >
                      <div className="inner">
                        <div className="tag">
                          <span>#</span> JavaScript
                        </div>
                        <div className="tag">
                          <span>#</span> Reactjs
                        </div>
                        <div className="tag">
                          <span>#</span> Typescript
                        </div>
                        <div className="tag">
                          <span>#</span> Next.js
                        </div>
                        <div className="tag">
                          <span>#</span> HTML
                        </div>
                        {/* duplicated content */}
                        <div className="tag">
                          <span>#</span> CSS
                        </div>
                        <div className="tag">
                          <span>#</span> Bootstrap
                        </div>
                        <div className="tag">
                          <span>#</span> Tailwind CSS
                        </div>
                        <div className="tag">
                          <span>#</span> Git
                        </div>
                        <div className="tag">
                          <span>#</span> Bitbucket
                        </div>
                      </div>
                    </div>

                    <div
                      className="loop-slider"
                      style={{
                        "--duration": "15951ms",
                        "--direction": "reverse",
                      }}
                    >
                      <div className="inner">
                        <div className="tag">
                          <span>#</span> JavaScript
                        </div>
                        <div className="tag">
                          <span>#</span> Reactjs
                        </div>
                        <div className="tag">
                          <span>#</span> Typescript
                        </div>
                        <div className="tag">
                          <span>#</span> Next.js
                        </div>
                        <div className="tag">
                          <span>#</span> HTML
                        </div>
                        {/* duplicated content */}
                        <div className="tag">
                          <span>#</span> CSS
                        </div>
                        <div className="tag">
                          <span>#</span> Bootstrap
                        </div>
                        <div className="tag">
                          <span>#</span> Tailwind CSS
                        </div>
                        <div className="tag">
                          <span>#</span> Git
                        </div>
                        <div className="tag">
                          <span>#</span> Bitbucket
                        </div>
                      </div>
                    </div>

                    <div
                      className="loop-slider"
                      style={{
                        "--duration": "15951ms",
                        "--direction": "normal",
                      }}
                    >
                      <div className="inner">
                        <div className="tag">
                          <span>#</span> JavaScript
                        </div>
                        <div className="tag">
                          <span>#</span> Reactjs
                        </div>
                        <div className="tag">
                          <span>#</span> Typescript
                        </div>
                        <div className="tag">
                          <span>#</span> Next.js
                        </div>
                        <div className="tag">
                          <span>#</span> HTML
                        </div>
                        {/* duplicated content */}
                        <div className="tag">
                          <span>#</span> CSS
                        </div>
                        <div className="tag">
                          <span>#</span> Bootstrap
                        </div>
                        <div className="tag">
                          <span>#</span> Tailwind CSS
                        </div>
                        <div className="tag">
                          <span>#</span> Git
                        </div>
                        <div className="tag">
                          <span>#</span> Bitbucket
                        </div>
                      </div>
                    </div>

                    <div
                      className="loop-slider"
                      style={{
                        "--duration": "15951ms",
                        "--direction": "reverse",
                      }}
                    >
                      <div className="inner">
                        <div className="tag">
                          <span>#</span> JavaScript
                        </div>
                        <div className="tag">
                          <span>#</span> Reactjs
                        </div>
                        <div className="tag">
                          <span>#</span> Typescript
                        </div>
                        <div className="tag">
                          <span>#</span> Next.js
                        </div>
                        <div className="tag">
                          <span>#</span> HTML
                        </div>
                        {/* duplicated content */}
                        <div className="tag">
                          <span>#</span> CSS
                        </div>
                        <div className="tag">
                          <span>#</span> Bootstrap
                        </div>
                        <div className="tag">
                          <span>#</span> Tailwind CSS
                        </div>
                        <div className="tag">
                          <span>#</span> Git
                        </div>
                        <div className="tag">
                          <span>#</span> Bitbucket
                        </div>
                      </div>
                    </div>

                    <div className="fade" />
                  </div>
                </div>

                <span id="scrollspyHeading3"></span>

                <div
                  className={`m-auto d-flex justify-content-center flex-column align-items-center mb-4  w-75`}
                >
                  <h3 className={styles.divMainText}>Projects</h3>

                  <div
                    id="carouselExampleAutoplaying"
                    className="carousel slide carousel-fade"
                    data-bs-ride="carousel"
                  >
                    <div className="carousel-inner">
                      {/* calculator  */}
                      <div className="carousel-item active">
                        <Image
                          className="img-fluid"
                          src={CalculatorImg}
                          width={1000}
                          height={1000}
                          alt="Calculator"
                          quality={100}
                        />
                        <div className="carousel-caption d-md-block">
                          <Link
                            className={styles.projectLink}
                            href="https://aquamarine-empanada-5035b3.netlify.app/"
                          >
                            {" "}
                            Calculator{" "}
                          </Link>
                        </div>
                      </div>
                      {/* dropbox  */}
                      <div className="carousel-item">
                        <Image
                          className="img-fluid"
                          src={DropboxImg}
                          width={1000}
                          height={1000}
                          alt="Calculator"
                          quality={100}
                        />
                        <div className="carousel-caption d-md-block">
                          <Link
                            className={styles.projectLink}
                            href="https://gilded-tapioca-6c76e2.netlify.app/"
                          >
                            {" "}
                            Dropbox Clone{" "}
                          </Link>
                        </div>
                      </div>

                      {/* dice game  */}
                      <div className="carousel-item">
                        <Image
                          className="img-fluid"
                          src={DiceGameImg}
                          width={1000}
                          height={1000}
                          alt="Calculator"
                          quality={100}
                        />
                        <div className="carousel-caption d-md-block">
                          <Link
                            className={styles.projectLink}
                            href="https://creative-torte-876dae.netlify.app/"
                          >
                            {" "}
                            Dice Game{" "}
                          </Link>
                        </div>
                      </div>

                      {/* land rover  */}
                      <div className="carousel-item">
                        <Image
                          className="img-fluid"
                          src={LandRoverImg}
                          width={1000}
                          height={1000}
                          alt="Calculator"
                          quality={100}
                        />
                        <div className="carousel-caption  d-md-block">
                          <Link
                            className={styles.projectLink}
                            href="https://hilarious-tanuki-a66ae7.netlify.app/"
                          >
                            {" "}
                            Landrover Website Clone{" "}
                          </Link>
                        </div>
                      </div>

                      {/* netflix  */}
                      <div className="carousel-item">
                        <Image
                          className="img-fluid"
                          src={NetflixImg}
                          width={1000}
                          height={1000}
                          alt="Calculator"
                          quality={100}
                        />
                        <div className="carousel-caption d-md-block">
                          <Link
                            className={styles.projectLink}
                            href="https://stellular-tartufo-a3bb3d.netlify.app/"
                          >
                            {" "}
                            Netflix Clone{" "}
                          </Link>
                        </div>
                      </div>
                    </div>
                    <button
                      className="carousel-control-prev"
                      type="button"
                      data-bs-target="#carouselExampleAutoplaying"
                      data-bs-slide="prev"
                    >
                      <span
                        className="carousel-control-prev-icon"
                        aria-hidden="true"
                      />
                      <span className="visually-hidden">Previous</span>
                    </button>
                    <button
                      className="carousel-control-next"
                      type="button"
                      data-bs-target="#carouselExampleAutoplaying"
                      data-bs-slide="next"
                    >
                      <span
                        className="carousel-control-next-icon"
                        aria-hidden="true"
                      />
                      <span className="visually-hidden">Next</span>
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* social media Links  */}

          <div className="socialLinks">
            <ul className=" px-1 py-0 mx-1">
              <li>
                <a
                  className="social-icons"
                  href="https://www.github.com/kirangawande0176"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  {" "}
                  <Image
                    className="img-fluid "
                    src={GitImg}
                    alt="git-hub"
                    loading="lazy"
                    height={25}
                    width={25}
                  />{" "}
                </a>
              </li>
              <li>
                <a
                  className="social-icons"
                  href="https://www.linkedin.com/in/kiran-gawande-b3a965199?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  {" "}
                  <Image
                    className="img-fluid"
                    src={LinkedIn}
                    alt="linkedin"
                    loading="lazy"
                    height={25}
                    width={25}
                  />{" "}
                </a>
              </li>
              <li>
                {" "}
                <a
                  className="social-icons"
                  target="_blank"
                  href="https://www.instagram.com/kirangawande0176?igsh=MTEwd3VtcDhoeTNreQ=="
                  rel="noopener noreferrer"
                >
                  {" "}
                  <Image
                    className="img-fluid"
                    src={Instagram}
                    alt="instagram"
                    loading="lazy"
                    height={25}
                    width={25}
                  />{" "}
                </a>
              </li>
              <li>
                <a
                  className="social-icons"
                  href="https://wa.me/9769650176"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  {" "}
                  <Image
                    className="img-fluid"
                    src={Whatsapp}
                    alt="whatsapp"
                    loading="lazy"
                    height={25}
                    width={25}
                  />{" "}
                </a>
              </li>
            </ul>
          </div>
        </main>
        <footer className={styles.footer}>
          <h5 className={` ${styles.bottomHeading}  my-3 mx-3`}>
            Kiran Gawande
          </h5>
          <p className={` ${styles.footerPara}  my-3 mx-3`}>
            {/* © 2021 Kiran Gawande. All Rights Reserved. */}
            <a
              className="text-black align-items-center fw-bolder text-decoration-none"
              href="mailto:kirangawande0176@gmail.com"
            >
              {" "}
              <MdMarkEmailRead /> kirangawande0176@gmail.com
            </a>
          </p>
        </footer>
      </div>
    </>
  );
}

{
  /* <div className="carousel-item active">
<Image className="img-fluid" src={CalculatorImg} width={1000} height={1000} alt="Calculator" quality={100} />
<div className="carousel-caption d-none d-md-block">
<Link className={styles.projectLink} href="https://aquamarine-empanada-5035b3.netlify.app/"> Calculator </Link>
  <p>
   Calculator in javascript
  </p>
</div>
</div> */
}
